site_name: side-projects/leetcode
docs_dir: docs
nav:
  - index.md
  - 15 Patterns:
    - Two Pointers:
      - 1-two-sum/README.md
      - 167-two-sum-ii-input-array-is-sorted/README.md
      - 15-3sum/README.md
      - 11-container-with-most-water/README.md
    - Overlapping Intervals:
      - 56-merge-intervals/README.md
      - 57-insert-interval/README.md
      - 435-non-overlapping-intervals/README.md
    - Sliding Window:
      - 643-maximum-average-subarray-i/README.md
      - 3-longest-substring-without-repeating-characters/README.md
      - 76-minimum-window-substring/README.md
    - Prefix Sum:
      - 303-range-sum-query-immutable/README.md
      - 525-contiguous-array/README.md
      - 560-subarray-sum-equals-k/README.md
    - Fast and Slow Pointers:
      - 141-linked-list-cycle/README.md
      - 202-happy-number/README.md
      - 287-find-the-duplicate-number/README.md
    - Linkedin List In-place Reversal:
      - 206-reverse-linked-list/README.md
      - 92-reverse-linked-list-ii/README.md
      - 24-swap-nodes-in-pairs/README.md
    - Monotonic Stack:
      - 496-next-greater-element-i/README.md
      - 739-daily-temperatures/README.md
      - 84-largest-rectangle-in-histogram/README.md
    - Top K Elements:
      - 215-kth-largest-element-in-an-array/README.md
      - 347-top-k-frequent-elements/README.md
      - 373-find-k-pairs-with-smallest-sums/README.md
