site_name: side-projects/leetcode
docs_dir: docs
nav:
  - index.md
  - 15 Patterns:
    - Two Pointers:
      - 1-two-sum/README.md
      - 167-two-sum-ii-input-array-is-sorted/README.md
      - 15-3sum/README.md
      - 11-container-with-most-water/README.md
    - Overlapping Intervals:
      - 56-merge-intervals/README.md
      - 57-insert-interval/README.md
      - 435-non-overlapping-intervals/README.md
    - Sliding Window:
      - 643-maximum-average-subarray-i/README.md
      - 3-longest-substring-without-repeating-characters/README.md
      - 76-minimum-window-substring/README.md
    - Prefix Sum:
      - 303-range-sum-query-immutable/README.md
      - 525-contiguous-array/README.md
      - 560-subarray-sum-equals-k/README.md
    - Fast and Slow Pointers:
      - 141-linked-list-cycle/README.md
      - 202-happy-number/README.md
      - 287-find-the-duplicate-number/README.md
    - Linkedin List In-place Reversal:
      - 206-reverse-linked-list/README.md
      - 92-reverse-linked-list-ii/README.md
      - 24-swap-nodes-in-pairs/README.md
    - Monotonic Stack:
      - 496-next-greater-element-i/README.md
      - 739-daily-temperatures/README.md
      - 84-largest-rectangle-in-histogram/README.md
    - Top K Elements:
      - 215-kth-largest-element-in-an-array/README.md
      - 347-top-k-frequent-elements/README.md
      - 373-find-k-pairs-with-smallest-sums/README.md
    - Dynamic Programming:
      - 70-climbing-stairs/README.md
      - 322-coin-change/README.md
      - 300-longest-increasing-subsequence/README.md
      - 312-burst-balloons/README.md
      - 416-partition-equal-subset-sum/README.md
      - 1143-longest-common-subsequence/README.md
    - Backtracking:
      - 46-permutations/README.md
      - 78-subsets/README.md
      - 51-n-queens/README.md
    - Binary Search:
      - 374-guess-number-higher-or-lower/README.md
      - 2300-successful-pairs-of-spells-and-potions/README.md
      - 162-find-peak-element/README.md
      - 875-koko-eating-bananas/README.md
    - Modified Binary Search:
      - 33-search-in-rotated-sorted-array/README.md
      - 153-find-minimum-in-rotated-sorted-array/README.md
      - 240-search-a-2d-matrix-ii/README.md
    - Binary Tree Traversal:
      - 257-binary-tree-paths/README.md
      - 230-kth-smallest-element-in-a-bst/README.md
      - 124-binary-tree-maximum-path-sum/README.md
      - 107-binary-tree-level-order-traversal-ii/README.md
    - DFS:
      - 133-clone-graph/README.md
      - 113-path-sum-ii/README.md
      - 210-course-schedule-ii/README.md
    - BFS:
      - 102-binary-tree-level-order-traversal/README.md
      - 994-rotting-oranges/README.md
      - 127-word-ladder/README.md
    - Matrix Traversal:
      - 733-flood-fill/README.md
      - 200-number-of-islands/README.md
      - 130-surrounded-regions/README.md